### ISSUE TITLE
Linter does not warn on missing image files

### ISSUE THREAD

**Issue by hroncok** [3DprintFIT/BI-3DT#11]

**Comment by syky27** [comment]
@mmajko  would you be willing to take a look at this?

Thanks

**Comment by marianhlavac** [comment]
sure, hope I won't forget.

will put reminder on my to-do list

**Comment by hroncok** [comment]
Linter is gone. Kinda reopened as https://gitlab.fit.cvut.cz/course-pages/course-pages/issues/84
