### ISSUE TITLE
Unreachable content

### ISSUE THREAD

**Issue by hroncok** [3DprintFIT/BI-3DT#60]
We should make sure all content is reachable from index.md via a series of links. In other words, we should check that every link was resolved at least once when we start resolving from index.md.

**Comment by syky27** [comment]
I could write scraper like this in about 5 minutes... We should check Edux not this repo.

**Comment by hroncok** [comment]
I could as well. But there's no need yet.

Dne 29. 9. 2017 21:40 napsal uživatel "Tomas Sykora, jr." <
notifications@github.com>:

**Comment by hroncok** [comment]
Course pages navigation should solve this for us.
