### ISSUE TITLE
Old teacher data

### ISSUE THREAD

**Issue by hroncok** [3DprintFIT/BI-3DT#61]

**Comment by Hanyman8** [comment]
Done

**Comment by marianhlavac** [comment]
Uh-huh.

**Comment by syky27** [comment]
Will do, tomorrow at 9am, I will already be in the office, if ok?

**Comment by hroncok** [comment]
Right, sorry for closing early.

**Comment by syky27** [comment]
No worries

**Comment by hroncok** [comment]
@syky27 bump

**Comment by hroncok** [comment]
@syky27 bump

**Comment by syky27** [comment]
Dammit I always seem to forget this, will do when I’ll be at the desk.

**Comment by syky27** [comment]
5eba667838ea77aac9d66688cf618931aef225d6
