### ISSUE TITLE
Renew 3D scanning content

### ISSUE THREAD

**Issue by hroncok** [3DprintFIT/BI-3DT#63]

**Comment by hroncok** [comment]
Note: We might dedicate 3 points to this, if we turn all 4 points to 3. But if we decide to do this, we need to do it very soon.

**Comment by hroncok** [comment]
acked IRL

**Comment by syky27** [comment]
@hroncok I dont minf having this in our tutorials, how about you?

**Comment by hroncok** [comment]
JFYI I have just met with @jakubprusa and he will provide the tutorial. It will be about mesh reconstruction from point cloud in MeshLab and CloudCompare.

**Comment by hroncok** [comment]
Points were adjusted in aff4c6c00ea25bbfe5b837eea647a8de42d033bb

**Comment by syky27** [comment]
Done, than. Thanks @jakubprusa

**Comment by hroncok** [comment]
@jakubprusa bump?

**Comment by hroncok** [comment]
@jakubprusa bump?

**Comment by hroncok** [comment]
@jakubprusa what's the status?

**Comment by hroncok** [comment]
Fixed in https://github.com/3DprintFIT/BI-3DT/pull/93
